### ISSUE TITLE
Empty CDT directory? (Moving from https://github.com/grame-cncm/faust/pull/870)

### ISSUE THREAD

**Issue by khiner** [GATech-CSE-6730-Spring-2023-Project/mesh2audio#2]
@josmithiii  Moving mesh2audio build issue discussion here.

**Comment by khiner** [comment]
I noticed a couple of out-of-date bits in the build section of the readme that may or may not be playing a role. I just clean-cloned and built again on my machine and everything ran successfully (also on an M1), and here was my entire process:

```shell
$ git clone --recurse-submodules git@github.com:GATech-CSE-6730-Spring-2023-Project/mesh2audio.git
$ cd mesh2audio
$ ls app/lib/CDT/CDT # Non-empty
$ brew install glew llvm eigen # Reinstall just in case newer libs are somehow an issue
$ brew link llvm --force
$ cd app
$ ./script/Build
$ cd build
$ ./mesh2audio
```

**Comment by josmithiii** [comment]
> How about just lib/CDT/CDT - is that empty?

lib/CDT/ is empty, as if the submodule were never downloaded, but the other submodules all appeared to be healthy, containing files.   I cloned first non-recursively, replaced the faust submodule directory with a symlink to my existing master-dev clone, and did a recursive pull after that, but that shouldn't matter.  CDT is the only empty directory after my recursive pull.

The fresh clone is still downloading.  I interrupted the original clone when it got to Faust, and resumed it after creating the Faust symlink.  Maybe that was the problem?  I'll wait for this one but will have to report on it later.

**Comment by khiner** [comment]
> The fresh clone is still downloading. I interrupted the original clone when it got to Faust, and resumed it after creating the Faust symlink.

Ah, that must be it. I just got to experience just how many dependencies this repo has again myself, it really is a long wait. A couple of these should probably turn into more brew dependencies instead of pulling in the source, but that has its own set of issues. Hoping the new clone at least gets you past this step 🤞

**Comment by josmithiii** [comment]
Ok that was it.  I have no idea how interrupting the Faust download corrupted CDT.

**Comment by khiner** [comment]
Ok great! All working then, getting audio etc?

**Comment by josmithiii** [comment]
Yes, generate mesh, DSP, click, sound!
Next would be to put it in an audio plugin...

**Comment by khiner** [comment]
Glad to hear it! Agreed, it would be nice to have this in plug-in form and seems doable, probably easiest with Clap - maybe someday :)
